# Generated by Django 2.1.2 on 2018-10-09 08:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contract', '0002_auto_20181008_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccept',
            name='email',
            field=models.EmailField(db_index=True, default='q@re.ru', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccept',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='useraccept',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='useraccept',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
