# Generated by Django 2.1.4 on 2018-12-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contract', '0004_auto_20181204_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccept',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
