# Generated by Django 2.1.4 on 2018-12-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contract', '0010_auto_20181210_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccept',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], default=5),
        ),
    ]
